# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - checklist-subje

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
  
    - name: Install dependencies
      run: |
        npm install
        npm install -g gatsby-cli
    - name: Build with Gatsby
      run: gatsby build

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'checklist-subje'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_dfee26a01c034f6080a3b36a4bfc19d8 }}
        package: .